layout_spectrum: 0.1989247
color:
  saturation: 0.3763441
  brandStrength: 0.7534028
  lightness: 0.6290323
  rhythmicContrast: 0.4874552
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.8817204
name: Driven ideas
